version: '3.4'

services:
  easyrank.web:
    image: ${DOCKER_REGISTRY-}easyrankweb
    build:
      context: .
      dockerfile: EasyRank.Web/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    #container_name: EasyRank-Db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=VerySecure!DbPassword123
    ports:
      - '1433:1433'